// training-data.js — ~300 labeled examples across 6 emotions
// Each entry: { text, emotion }
// Emotions: joy, anger, sadness, surprise, fear, neutral

export const EMOTIONS = ['joy', 'anger', 'sadness', 'surprise', 'fear', 'neutral'];

export const trainingData = [
  // === JOY (50) ===
  { text: "I am so happy today", emotion: "joy" },
  { text: "This is wonderful news", emotion: "joy" },
  { text: "I love this so much", emotion: "joy" },
  { text: "What a beautiful day", emotion: "joy" },
  { text: "I feel amazing right now", emotion: "joy" },
  { text: "This makes me smile", emotion: "joy" },
  { text: "I am thrilled about this", emotion: "joy" },
  { text: "Everything is going great", emotion: "joy" },
  { text: "I am overjoyed with the results", emotion: "joy" },
  { text: "This is the best thing ever", emotion: "joy" },
  { text: "I feel so blessed and grateful", emotion: "joy" },
  { text: "What a fantastic achievement", emotion: "joy" },
  { text: "I am delighted to hear that", emotion: "joy" },
  { text: "This brought me so much joy", emotion: "joy" },
  { text: "I feel wonderful and alive", emotion: "joy" },
  { text: "Such a pleasant surprise", emotion: "joy" },
  { text: "My heart is full of happiness", emotion: "joy" },
  { text: "I am ecstatic about this opportunity", emotion: "joy" },
  { text: "Life is truly beautiful", emotion: "joy" },
  { text: "I feel on top of the world", emotion: "joy" },
  { text: "This is absolutely delightful", emotion: "joy" },
  { text: "I am grateful for everything", emotion: "joy" },
  { text: "What a joyful moment", emotion: "joy" },
  { text: "I feel so lucky and blessed", emotion: "joy" },
  { text: "This is making my day", emotion: "joy" },
  { text: "I love spending time with friends", emotion: "joy" },
  { text: "The celebration was fantastic", emotion: "joy" },
  { text: "I feel cheerful and optimistic", emotion: "joy" },
  { text: "What an incredible experience", emotion: "joy" },
  { text: "I am laughing with pure joy", emotion: "joy" },
  { text: "This fills me with delight", emotion: "joy" },
  { text: "I feel great about our progress", emotion: "joy" },
  { text: "Everything worked out perfectly", emotion: "joy" },
  { text: "I am beaming with pride", emotion: "joy" },
  { text: "Such a lovely surprise gift", emotion: "joy" },
  { text: "I am excited and happy", emotion: "joy" },
  { text: "This is truly heartwarming", emotion: "joy" },
  { text: "I enjoy every moment of this", emotion: "joy" },
  { text: "The good news keeps coming", emotion: "joy" },
  { text: "I feel radiant with happiness", emotion: "joy" },
  { text: "What a glorious morning", emotion: "joy" },
  { text: "I appreciate all the kindness", emotion: "joy" },
  { text: "This is pure bliss", emotion: "joy" },
  { text: "I am having the time of my life", emotion: "joy" },
  { text: "Everything is falling into place", emotion: "joy" },
  { text: "I am so pleased with the outcome", emotion: "joy" },
  { text: "This party is amazing", emotion: "joy" },
  { text: "I feel content and peaceful", emotion: "joy" },
  { text: "My dreams are coming true", emotion: "joy" },
  { text: "I am grinning from ear to ear", emotion: "joy" },

  // === ANGER (50) ===
  { text: "This makes me so angry", emotion: "anger" },
  { text: "I am furious about this", emotion: "anger" },
  { text: "How dare they do that", emotion: "anger" },
  { text: "I am outraged by this behavior", emotion: "anger" },
  { text: "This is absolutely infuriating", emotion: "anger" },
  { text: "I hate when this happens", emotion: "anger" },
  { text: "I am livid right now", emotion: "anger" },
  { text: "This is completely unacceptable", emotion: "anger" },
  { text: "I want to scream in frustration", emotion: "anger" },
  { text: "They have no right to do this", emotion: "anger" },
  { text: "I am seething with rage", emotion: "anger" },
  { text: "This injustice makes me furious", emotion: "anger" },
  { text: "How could they be so reckless", emotion: "anger" },
  { text: "I am fed up with this nonsense", emotion: "anger" },
  { text: "This is driving me insane", emotion: "anger" },
  { text: "I despise their attitude", emotion: "anger" },
  { text: "What a terrible and unfair decision", emotion: "anger" },
  { text: "I am boiling with anger", emotion: "anger" },
  { text: "This is a complete disgrace", emotion: "anger" },
  { text: "I cannot tolerate this anymore", emotion: "anger" },
  { text: "They ruined everything", emotion: "anger" },
  { text: "I am enraged by their lies", emotion: "anger" },
  { text: "This betrayal is unforgivable", emotion: "anger" },
  { text: "I am so frustrated and mad", emotion: "anger" },
  { text: "How stupid can they be", emotion: "anger" },
  { text: "I want revenge for this", emotion: "anger" },
  { text: "This is absolutely ridiculous", emotion: "anger" },
  { text: "I am annoyed beyond measure", emotion: "anger" },
  { text: "They should be ashamed of themselves", emotion: "anger" },
  { text: "This makes my blood boil", emotion: "anger" },
  { text: "I am hostile toward their actions", emotion: "anger" },
  { text: "What an outrageous thing to say", emotion: "anger" },
  { text: "I am bitterly resentful", emotion: "anger" },
  { text: "They deliberately sabotaged us", emotion: "anger" },
  { text: "I am losing my patience", emotion: "anger" },
  { text: "This corruption makes me sick", emotion: "anger" },
  { text: "I demand answers right now", emotion: "anger" },
  { text: "How infuriating and disrespectful", emotion: "anger" },
  { text: "I am aggravated by their incompetence", emotion: "anger" },
  { text: "This is the last straw", emotion: "anger" },
  { text: "I am irritated by this delay", emotion: "anger" },
  { text: "They are being completely unreasonable", emotion: "anger" },
  { text: "I am incensed by this negligence", emotion: "anger" },
  { text: "What a horrible thing to do", emotion: "anger" },
  { text: "I resent their arrogance", emotion: "anger" },
  { text: "This incompetence is maddening", emotion: "anger" },
  { text: "I am disgusted by their greed", emotion: "anger" },
  { text: "They wasted everyone's time", emotion: "anger" },
  { text: "I am wrathful and indignant", emotion: "anger" },
  { text: "This blatant disregard is appalling", emotion: "anger" },

  // === SADNESS (50) ===
  { text: "I feel so sad and lonely", emotion: "sadness" },
  { text: "This is heartbreaking news", emotion: "sadness" },
  { text: "I am devastated by this loss", emotion: "sadness" },
  { text: "Everything feels hopeless right now", emotion: "sadness" },
  { text: "I cannot stop crying", emotion: "sadness" },
  { text: "I miss them so much", emotion: "sadness" },
  { text: "My heart is broken", emotion: "sadness" },
  { text: "I feel empty inside", emotion: "sadness" },
  { text: "This is the saddest day of my life", emotion: "sadness" },
  { text: "I am grieving deeply", emotion: "sadness" },
  { text: "I feel so depressed and down", emotion: "sadness" },
  { text: "Nothing seems to matter anymore", emotion: "sadness" },
  { text: "I am overwhelmed with sorrow", emotion: "sadness" },
  { text: "The pain is unbearable", emotion: "sadness" },
  { text: "I feel so alone in this world", emotion: "sadness" },
  { text: "This farewell is too painful", emotion: "sadness" },
  { text: "I am mourning the loss", emotion: "sadness" },
  { text: "Everything I loved is gone", emotion: "sadness" },
  { text: "I feel hollow and numb", emotion: "sadness" },
  { text: "This tragedy has shattered me", emotion: "sadness" },
  { text: "I am crying myself to sleep", emotion: "sadness" },
  { text: "The world feels dark and cold", emotion: "sadness" },
  { text: "I have lost all hope", emotion: "sadness" },
  { text: "This disappointment crushed me", emotion: "sadness" },
  { text: "I feel worthless and abandoned", emotion: "sadness" },
  { text: "I am suffering in silence", emotion: "sadness" },
  { text: "Nothing brings me comfort", emotion: "sadness" },
  { text: "I am heartbroken about the ending", emotion: "sadness" },
  { text: "The memories make me weep", emotion: "sadness" },
  { text: "I feel defeated and lost", emotion: "sadness" },
  { text: "This grief is consuming me", emotion: "sadness" },
  { text: "I am drowning in despair", emotion: "sadness" },
  { text: "Everything reminds me of what I lost", emotion: "sadness" },
  { text: "I feel melancholy and blue", emotion: "sadness" },
  { text: "This misery never ends", emotion: "sadness" },
  { text: "I am burdened with regret", emotion: "sadness" },
  { text: "The loneliness is crushing", emotion: "sadness" },
  { text: "I feel so helpless and small", emotion: "sadness" },
  { text: "All the joy has drained away", emotion: "sadness" },
  { text: "I am inconsolable with grief", emotion: "sadness" },
  { text: "This loss leaves a deep wound", emotion: "sadness" },
  { text: "I feel downcast and gloomy", emotion: "sadness" },
  { text: "My spirit is completely crushed", emotion: "sadness" },
  { text: "I weep for what could have been", emotion: "sadness" },
  { text: "This emptiness is overwhelming", emotion: "sadness" },
  { text: "I am profoundly unhappy", emotion: "sadness" },
  { text: "The tears will not stop flowing", emotion: "sadness" },
  { text: "I feel like giving up on everything", emotion: "sadness" },
  { text: "This separation is agonizing", emotion: "sadness" },
  { text: "I am filled with deep sorrow", emotion: "sadness" },

  // === SURPRISE (50) ===
  { text: "I cannot believe this happened", emotion: "surprise" },
  { text: "What an unexpected turn of events", emotion: "surprise" },
  { text: "I am completely shocked", emotion: "surprise" },
  { text: "This is unbelievable", emotion: "surprise" },
  { text: "I did not see that coming at all", emotion: "surprise" },
  { text: "Wow I am speechless", emotion: "surprise" },
  { text: "This caught me totally off guard", emotion: "surprise" },
  { text: "I am stunned by this revelation", emotion: "surprise" },
  { text: "No way that actually happened", emotion: "surprise" },
  { text: "I am astonished by the results", emotion: "surprise" },
  { text: "This is mind blowing news", emotion: "surprise" },
  { text: "I never expected this outcome", emotion: "surprise" },
  { text: "What a shocking discovery", emotion: "surprise" },
  { text: "I am taken aback completely", emotion: "surprise" },
  { text: "This changes everything suddenly", emotion: "surprise" },
  { text: "I am amazed at what just happened", emotion: "surprise" },
  { text: "How did that even happen", emotion: "surprise" },
  { text: "This is truly remarkable and unexpected", emotion: "surprise" },
  { text: "I am bewildered by this turn", emotion: "surprise" },
  { text: "Nobody predicted this would occur", emotion: "surprise" },
  { text: "I am flabbergasted right now", emotion: "surprise" },
  { text: "That came out of nowhere", emotion: "surprise" },
  { text: "I am startled by the sudden change", emotion: "surprise" },
  { text: "This is the last thing I expected", emotion: "surprise" },
  { text: "I am dumbfounded by their announcement", emotion: "surprise" },
  { text: "What a twist in the story", emotion: "surprise" },
  { text: "I am in complete disbelief", emotion: "surprise" },
  { text: "This revelation is staggering", emotion: "surprise" },
  { text: "I never imagined this was possible", emotion: "surprise" },
  { text: "How surprising and unusual", emotion: "surprise" },
  { text: "I am awestruck by the magnitude", emotion: "surprise" },
  { text: "This defies all expectations", emotion: "surprise" },
  { text: "I was not prepared for this at all", emotion: "surprise" },
  { text: "What an extraordinary coincidence", emotion: "surprise" },
  { text: "I am gobsmacked by the news", emotion: "surprise" },
  { text: "This is beyond anything I imagined", emotion: "surprise" },
  { text: "I was blindsided by this development", emotion: "surprise" },
  { text: "How peculiar and strange", emotion: "surprise" },
  { text: "I am thunderstruck by this event", emotion: "surprise" },
  { text: "This plot twist is insane", emotion: "surprise" },
  { text: "I cannot wrap my head around this", emotion: "surprise" },
  { text: "What an anomaly this turned out to be", emotion: "surprise" },
  { text: "I am dazed by the sudden news", emotion: "surprise" },
  { text: "This is genuinely surprising to me", emotion: "surprise" },
  { text: "I had no idea this would happen", emotion: "surprise" },
  { text: "Out of the blue everything changed", emotion: "surprise" },
  { text: "I am mystified by these results", emotion: "surprise" },
  { text: "That was a real jaw dropper", emotion: "surprise" },
  { text: "Who would have thought this possible", emotion: "surprise" },
  { text: "I am utterly baffled right now", emotion: "surprise" },

  // === FEAR (50) ===
  { text: "I am terrified right now", emotion: "fear" },
  { text: "This is really scary and frightening", emotion: "fear" },
  { text: "I feel so afraid and anxious", emotion: "fear" },
  { text: "Something terrible is about to happen", emotion: "fear" },
  { text: "I am trembling with fear", emotion: "fear" },
  { text: "This situation is extremely dangerous", emotion: "fear" },
  { text: "I feel threatened and unsafe", emotion: "fear" },
  { text: "I am dreading what comes next", emotion: "fear" },
  { text: "The darkness is closing in", emotion: "fear" },
  { text: "I am paralyzed with fright", emotion: "fear" },
  { text: "I am worried something bad will happen", emotion: "fear" },
  { text: "This gives me the chills", emotion: "fear" },
  { text: "I feel panicked and overwhelmed", emotion: "fear" },
  { text: "There is danger lurking everywhere", emotion: "fear" },
  { text: "I am horrified by what I saw", emotion: "fear" },
  { text: "I cannot shake this feeling of dread", emotion: "fear" },
  { text: "This is making me very nervous", emotion: "fear" },
  { text: "I am scared of what might happen", emotion: "fear" },
  { text: "The threat is growing stronger", emotion: "fear" },
  { text: "I am petrified and cannot move", emotion: "fear" },
  { text: "I feel vulnerable and exposed", emotion: "fear" },
  { text: "This creepy situation is unsettling", emotion: "fear" },
  { text: "I am anxious about the outcome", emotion: "fear" },
  { text: "The uncertainty fills me with terror", emotion: "fear" },
  { text: "I am frightened beyond words", emotion: "fear" },
  { text: "Something sinister is happening", emotion: "fear" },
  { text: "I am shaking and cannot calm down", emotion: "fear" },
  { text: "This nightmare feels so real", emotion: "fear" },
  { text: "I am fearful for my safety", emotion: "fear" },
  { text: "The eerie silence is disturbing", emotion: "fear" },
  { text: "I am alarmed by these warning signs", emotion: "fear" },
  { text: "I feel a deep sense of foreboding", emotion: "fear" },
  { text: "This horror is too much to bear", emotion: "fear" },
  { text: "I am quaking in my boots", emotion: "fear" },
  { text: "The menacing presence is terrifying", emotion: "fear" },
  { text: "I am filled with apprehension", emotion: "fear" },
  { text: "This ominous feeling will not go away", emotion: "fear" },
  { text: "I dread facing this alone", emotion: "fear" },
  { text: "I am spooked by the strange noises", emotion: "fear" },
  { text: "The risk of failure scares me deeply", emotion: "fear" },
  { text: "I am cowering in fear", emotion: "fear" },
  { text: "This phobia controls my life", emotion: "fear" },
  { text: "I am on edge and hypervigilant", emotion: "fear" },
  { text: "The looming threat is overwhelming", emotion: "fear" },
  { text: "I feel a chill running down my spine", emotion: "fear" },
  { text: "I am afraid of the unknown", emotion: "fear" },
  { text: "This feels like walking into a trap", emotion: "fear" },
  { text: "I am in a state of pure panic", emotion: "fear" },
  { text: "The impending doom weighs on me", emotion: "fear" },
  { text: "I am distressed and full of worry", emotion: "fear" },

  // === NEUTRAL (50) ===
  { text: "The meeting is scheduled for tomorrow", emotion: "neutral" },
  { text: "I went to the store today", emotion: "neutral" },
  { text: "The weather is cloudy with some rain", emotion: "neutral" },
  { text: "I need to finish this report by Friday", emotion: "neutral" },
  { text: "The train arrives at three o clock", emotion: "neutral" },
  { text: "I had a sandwich for lunch", emotion: "neutral" },
  { text: "The conference room is on the second floor", emotion: "neutral" },
  { text: "I will send the email after the call", emotion: "neutral" },
  { text: "The document has been updated", emotion: "neutral" },
  { text: "I read an article about technology", emotion: "neutral" },
  { text: "The project status is on track", emotion: "neutral" },
  { text: "I have a dentist appointment next week", emotion: "neutral" },
  { text: "The package should arrive on Monday", emotion: "neutral" },
  { text: "I parked the car in the garage", emotion: "neutral" },
  { text: "The instructions are in the manual", emotion: "neutral" },
  { text: "I took notes during the lecture", emotion: "neutral" },
  { text: "The file is saved in the shared folder", emotion: "neutral" },
  { text: "I walked the dog this morning", emotion: "neutral" },
  { text: "The highway has some construction work", emotion: "neutral" },
  { text: "I ordered supplies for the office", emotion: "neutral" },
  { text: "The presentation is forty slides long", emotion: "neutral" },
  { text: "I checked the inventory numbers", emotion: "neutral" },
  { text: "The system update is available now", emotion: "neutral" },
  { text: "I printed the documents for review", emotion: "neutral" },
  { text: "The library closes at nine pm", emotion: "neutral" },
  { text: "I organized the files alphabetically", emotion: "neutral" },
  { text: "The temperature is seventy two degrees", emotion: "neutral" },
  { text: "I filled out the registration form", emotion: "neutral" },
  { text: "The bus stop is two blocks away", emotion: "neutral" },
  { text: "I set an alarm for six am", emotion: "neutral" },
  { text: "The database contains ten thousand records", emotion: "neutral" },
  { text: "I prepared the agenda for the meeting", emotion: "neutral" },
  { text: "The server is running the latest version", emotion: "neutral" },
  { text: "I signed the contract this afternoon", emotion: "neutral" },
  { text: "The calendar shows three appointments", emotion: "neutral" },
  { text: "I watered the plants on the balcony", emotion: "neutral" },
  { text: "The report includes quarterly figures", emotion: "neutral" },
  { text: "I reviewed the pull request changes", emotion: "neutral" },
  { text: "The elevator is currently out of service", emotion: "neutral" },
  { text: "I returned the books to the shelf", emotion: "neutral" },
  { text: "The spreadsheet has twelve columns", emotion: "neutral" },
  { text: "I scheduled a follow up for next Tuesday", emotion: "neutral" },
  { text: "The backup completed successfully", emotion: "neutral" },
  { text: "I cleaned the kitchen after dinner", emotion: "neutral" },
  { text: "The network connection is stable", emotion: "neutral" },
  { text: "I summarized the key discussion points", emotion: "neutral" },
  { text: "The software version is two point five", emotion: "neutral" },
  { text: "I configured the settings as requested", emotion: "neutral" },
  { text: "The shipping address is confirmed", emotion: "neutral" },
  { text: "I completed the survey as instructed", emotion: "neutral" },
];
